### ISSUE TITLE
Ambiguous names

### ISSUE THREAD

**Issue by berezovskyi** [eclipse/lyo.client#35]
I can't tell apart the old client from the new one just a few days after reading your email @jamsden about a proposed artefact naming.

I suggest:

- the old client needs to have either `-legacy` or `-wink` appended to its name
- the new client need to have either `-jaxrs` or `-ng` appended to its name.

Also, I would like to stop using OSLC4J term. It's confusing people because really there is no difference between Lyo and OSLC4J.

**Comment by berezovskyi** [comment]
For example: `lyo-client-wink` (or `lyo-client-legacy`) and `lyo-client-jaxrs`.

**Comment by jamsden** [comment]
I certainly agree this is confusing.

I use OSLC4J as the name of that subset of eclipse/Lyo that provides the Java SDK for client, server and TRS development. This seems useful as a name to describe what's in the SDK release. Lyo Designer is another nice name that identifies a different part of eclipse/Lyo. Validator, and Store are other related deliverables, all different than the SDK.

Maybe that's not accurate, but it seems useful.

Another option is to deprecate oslc-java-client, not include it in 4.0.0 and use oslc4j-client only in 4.0.0. 

What I'm trying to avoid is introducing any breaking API changes in in the old client. Changing old artifact names and changing OslcClient constructors in the old client would have been API breaking. I had hoped to just leave the old wink stuff alone.

I don't like naming things based on their implementation. lyo-client seems too broad, it only covers OSLC CRUD and discovery. I think we're stuck with oslc-java-client since we don't want to rename the old artifact. That's what lead to oslc4j-client.

**Comment by berezovskyi** [comment]
Jim, I only suggest to rename the `artifactId`. No package name changes.

**Comment by berezovskyi** [comment]
It means that when you upgrade you client dep to 4.0 you also need to change the artifactId in the POM file. Code won't break.

**Comment by jamsden** [comment]
pom.xml files that refer to the old client would need to be updated. That's what I was trying to avoid.

But I can change the oslc4j-client to something else since this is new. Not sure what would be better.

I can also change the new package names from org.eclipse.lyo.client.oslc to org.eclipse.lyo.oslc.client. That's a better name and would eliminate the overlap.

Want me to do that?

**Comment by berezovskyi** [comment]
Hmm, that's impossible to avoid. If you want to update 2.4 -> 4.0, you **have** to edit your POM. Let's have a chat about this tomorrow or on Fri during one of our calls.

**Comment by jamsden** [comment]
yes, but only to edit the OSLC4J version. you shouldn't have to change dependency names and be concerned your client apps won't compile or run - if we can help it.

**Comment by jamsden** [comment]
I renamed all toe packages in lyo.clint's oslc4j-client to org.eclipse.lyo.oslc4j.client.* to be consistent with lyo.core oslc4j-core's use of oslc4j, and to eliminate any name collisions with the old oslc-java-client.

**Comment by berezovskyi** [comment]
Just had to open the repo yesterday to check if the artifactid I had was for the new client or not. Definitely not OK if the newcomers also have to be get confused like that.

**Comment by jadelkhoury** [comment]
People shouldn't even need to access to repo. We need to update our wiki pages for 4.0.0 - both client and server. 
From our front page https://wiki.eclipse.org/Lyo, the client related content (https://wiki.eclipse.org/Lyo/BuildClient) is very obsolete. 

I can do a quick update.
But where should the pages be? I recall we said we move away from Eclipse wiki pages.
 
LyoDesigner has its pages under https://github.com/eclipse/lyo.designer/wiki.
Should each repo has its own wiki pages?
It would be good with a single such wiki location.

**Comment by jamsden** [comment]
https://github.com/eclipse/lyo could provide a launch point for related 
Wikies. 

Jim Amsden, Senior Technical Staff Member
OSLC and Linked Lifecycle Data
919-525-6575

**Comment by berezovskyi** [comment]
@jadelkhoury updating the docs would be very good! but the discussion here is that I want to rename the artifacts as descibed in earlier in this ticket.

@jamsden sure, we should make use of it!

**Comment by jamsden** [comment]
The artifactId for the old and new client are different, so I don't see why you'd need to open the repo to figure out which one you're using. They're certainly similar and we'd have to keep that clear in the documentation (of which there isn't any for the new client).

**Comment by berezovskyi** [comment]
I have also raised an issue that many classes are duplicated as a result of this "forking" of the old client. Can't readily find the issue no. Can we fix that?

**Comment by berezovskyi** [comment]
Re: artifactId. Yes, they are different but not distinctive enough for me to associate them with the new/old client without checking the README. In other words, they sound like clientA and clientB to me :)
